/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`test/export.ts TAP generates exports > /lib/index.ts 1`] = `
// DO NOT EDIT THIS FILE! It is automatically generated and changes WILL be overwritten

export { Prisma, PrismaClient, Author, Book, Review } from './client';
export * as Schemas from './schemas';
export type * from './types';

`
