import type { DMMF, GeneratorOptions } from '@prisma/generator-helper';
import { type ProjectOptions, IndentationText, QuoteKind } from 'ts-morph';
import { type FormatCodeSettings, SemicolonPreference } from 'typescript';

interface Config {
  output: string;
  clientPath: string;
}

export interface GenerateOptions {
  config: Config;
  formatSettings: FormatCodeSettings;
  projectSettings: ProjectOptions;
  models: DMMF.Model[];
  cwd: string;
  fileHeader: string;
}

export const getOptions = (options: GeneratorOptions): GenerateOptions => {
  const clientGenerator = options.otherGenerators.find((g) => g.provider.value === 'prisma-client-js');
  // istanbul ignore if - no need to test a thrown error
  if (!clientGenerator) {
    throw new Error('The prisma-client-js generator is required');
  }

  // istanbul ignore next - no need to test defaults
  const outputDir = options.generator.output?.value ?? './hapi';
  // istanbul ignore next - no need to test defaults
  const clientPath = clientGenerator.output?.value ?? './client';
  const result: GenerateOptions = {
    config: {
      output: outputDir,
      clientPath,
    },
    formatSettings: {
      indentSize: 2,
      tabSize: 2,
      semicolons: SemicolonPreference.Insert,
    },
    projectSettings: {
      manipulationSettings: {
        quoteKind: QuoteKind.Single,
        useTrailingCommas: true,
        indentationText: IndentationText.TwoSpaces,
      },
    },
    cwd: outputDir,
    models: options.dmmf.datamodel.models,
    fileHeader: '// DO NOT EDIT THIS FILE! It is automatically generated and changes WILL be overwritten',
  };

  // istanbul ignore else - this is literally always true in tests
  if (process.env.NODE_ENV === 'test') {
    result.projectSettings.useInMemoryFileSystem = true;
  }

  return result;
};

